export const ApiErrorCode = {
	UNAUTHORIZED: "UNAUTHORIZED",
	FORBIDDEN: "FORBIDDEN",
	INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
	TOKEN_INVALID: "TOKEN_INVALID",
	TOKEN_EXPIRED: "TOKEN_EXPIRED",
	INSUFFICIENT_PERMISSIONS: "INSUFFICIENT_PERMISSIONS",

	USER_NOT_FOUND: "USER_NOT_FOUND",
	USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
	EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",

	RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
	RESOURCE_CONFLICT: "RESOURCE_CONFLICT",
	RESOURCE_ALREADY_EXISTS: "RESOURCE_ALREADY_EXISTS",

	VALIDATION_ERROR: "VALIDATION_ERROR",
	INVALID_INPUT: "INVALID_INPUT",
	INVALID_REQUEST: "INVALID_REQUEST",

	INTERNAL_ERROR: "INTERNAL_ERROR",
	SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
	DATABASE_ERROR: "DATABASE_ERROR",
	RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
	QUOTA_EXCEEDED: "QUOTA_EXCEEDED",

	TOKEN_NOT_FOUND: "TOKEN_NOT_FOUND",
	TOKEN_CREATION_FAILED: "TOKEN_CREATION_FAILED",

	SUBSCRIPTION_NOT_FOUND: "SUBSCRIPTION_NOT_FOUND",
	SUBSCRIPTION_EXISTS: "SUBSCRIPTION_EXISTS",
	PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
} as const;

export type ApiErrorCodeType = (typeof ApiErrorCode)[keyof typeof ApiErrorCode];
